Slimmed down chunky compat
NillerMedDild/Enigmatica6 pull request #2181
Opened 2021-05-15 21:21 UTC by pm065

Now only includes loot tables. I may have forgotten to remove some things, not sure.
I've backed up the chunk _additions_ in a new branch so that I can transfer them to my own modpack, which also utilizes EE, and in case you change your mind :D

2021-05-15 21:22 UTC, pm065 commented
Oh yeah! I forgot the dimensional mineshaft!

2021-05-15 21:24 UTC, pm065 commented
Fixed now

2021-05-15 21:32 UTC, NillerMedDild requested changes

2021-05-15 21:32 UTC, NillerMedDild commented on kubejs/data/mythicbotany/loot_tables/blocks/elementium_ore.json
> +  }
Errr :P

2021-05-15 21:32 UTC, NillerMedDild commented on kubejs/data/mythicbotany/loot_tables/blocks/elementium_ore.json
> +            "name": "kubejs:elementium_chunk"
Erhm :P

2021-05-15 21:45 UTC, pm065 commented on kubejs/data/mythicbotany/loot_tables/blocks/elementium_ore.json
> +            "name": "kubejs:elementium_chunk"
oops

2021-05-15 21:46 UTC, pm065 commented
resolved!

2021-05-16 17:55 UTC, NillerMedDild approved these changes

2021-05-16 17:56 UTC, NillerMedDild commented
Thanks! :D

2021-05-16 17:56 UTC, merged