KubeJS Powah Coolants Script
NillerMedDild/Enigmatica6 pull request #3333
Opened 2021-09-29 01:48 UTC by MagisterXero

Added a script to allow the adding of solid coolants for Powah's Reactors
Please customize this as you'd like, these are really just reference points to use.

2021-09-29 02:24 UTC, MagisterXero commented
Also to note, this script is required on the Client side in order for players to see the coolant list, and not have some weird glitchy stuff when inserting/removing coolant items from reactors.

2021-09-30 06:47 UTC, NillerMedDild requested changes

2021-09-30 06:47 UTC, NillerMedDild commented on kubejs/config/common.properties
> +invertClassLoader=true
This setting change worries me to be honest 😄 
@TemperedFool did you create something that relied on this being false?

2021-09-30 06:48 UTC, NillerMedDild commented
Looks good to me, thanks for your contribution! :D I just gotta make sure the settings change doesn't interfere with anything else before I merge, sit tight 😄

2021-09-30 09:33 UTC, merged

2021-09-30 09:34 UTC, NillerMedDild commented on kubejs/config/common.properties
> +invertClassLoader=true
I asked on the KubeJS Discord and am no longer worried 😄